# On pi-node0:
 
# create munge key (if it is not already  autogenerated)
#sudo dd if=/dev/urandom bs=1 count=1024 > /etc/munge/munge.key
sudo chown munge:munge /etc/munge/munge.key
sudo chmod 400 /etc/munge/munge.key

# Copy munge key to the worker-nodes
for node in pi-node1 pi-node2 pi-node3; do
    sudo scp /etc/munge/munge.key admin@$node:/tmp/munge.key
done
